USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/allele.csv" AS row CREATE (n:allele) SET n = row;
RETURN 'Created allele nodes';
CREATE INDEX ON :allele(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/author.csv" AS row CREATE (n:author) SET n = row;
RETURN 'Created author nodes';
CREATE INDEX ON :author(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/bindingsite.csv" AS row CREATE (n:bindingsite) SET n = row;
RETURN 'Created bindingsite nodes';
CREATE INDEX ON :bindingsite(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/cdnaclone.csv" AS row CREATE (n:cdnaclone) SET n = row;
RETURN 'Created cdnaclone nodes';
CREATE INDEX ON :cdnaclone(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/cds.csv" AS row CREATE (n:cds) SET n = row;
RETURN 'Created cds nodes';
CREATE INDEX ON :cds(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosomaldeletion.csv" AS row CREATE (n:chromosomaldeletion) SET n = row;
RETURN 'Created chromosomaldeletion nodes';
CREATE INDEX ON :chromosomaldeletion(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosomalduplication.csv" AS row CREATE (n:chromosomalduplication) SET n = row;
RETURN 'Created chromosomalduplication nodes';
CREATE INDEX ON :chromosomalduplication(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosomalinversion.csv" AS row CREATE (n:chromosomalinversion) SET n = row;
RETURN 'Created chromosomalinversion nodes';
CREATE INDEX ON :chromosomalinversion(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosomaltranslocation.csv" AS row CREATE (n:chromosomaltranslocation) SET n = row;
RETURN 'Created chromosomaltranslocation nodes';
CREATE INDEX ON :chromosomaltranslocation(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosomaltransposition.csv" AS row CREATE (n:chromosomaltransposition) SET n = row;
RETURN 'Created chromosomaltransposition nodes';
CREATE INDEX ON :chromosomaltransposition(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosome.csv" AS row CREATE (n:chromosome) SET n = row;
RETURN 'Created chromosome nodes';
CREATE INDEX ON :chromosome(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosomeband.csv" AS row CREATE (n:chromosomeband) SET n = row;
RETURN 'Created chromosomeband nodes';
CREATE INDEX ON :chromosomeband(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/chromosomestructurevariation.csv" AS row CREATE (n:chromosomestructurevariation) SET n = row;
RETURN 'Created chromosomestructurevariation nodes';
CREATE INDEX ON :chromosomestructurevariation(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/comment.csv" AS row CREATE (n:comment) SET n = row;
RETURN 'Created comment nodes';
CREATE INDEX ON :comment(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/component.csv" AS row CREATE (n:component) SET n = row;
RETURN 'Created component nodes';
CREATE INDEX ON :component(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/crm.csv" AS row CREATE (n:crm) SET n = row;
RETURN 'Created crm nodes';
CREATE INDEX ON :crm(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/crossreference.csv" AS row CREATE (n:crossreference) SET n = row;
RETURN 'Created crossreference nodes';
CREATE INDEX ON :crossreference(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/databasereference.csv" AS row CREATE (n:databasereference) SET n = row;
RETURN 'Created databasereference nodes';
CREATE INDEX ON :databasereference(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/dataset.csv" AS row CREATE (n:dataset) SET n = row;
RETURN 'Created dataset nodes';
CREATE INDEX ON :dataset(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/datasource.csv" AS row CREATE (n:datasource) SET n = row;
RETURN 'Created datasource nodes';
CREATE INDEX ON :datasource(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/ecnumber.csv" AS row CREATE (n:ecnumber) SET n = row;
RETURN 'Created ecnumber nodes';
CREATE INDEX ON :ecnumber(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/enhancer.csv" AS row CREATE (n:enhancer) SET n = row;
RETURN 'Created enhancer nodes';
CREATE INDEX ON :enhancer(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/est.csv" AS row CREATE (n:est) SET n = row;
RETURN 'Created est nodes';
CREATE INDEX ON :est(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/exon.csv" AS row CREATE (n:exon) SET n = row;
RETURN 'Created exon nodes';
CREATE INDEX ON :exon(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/fiveprimeutr.csv" AS row CREATE (n:fiveprimeutr) SET n = row;
RETURN 'Created fiveprimeutr nodes';
CREATE INDEX ON :fiveprimeutr(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/forwardprimer.csv" AS row CREATE (n:forwardprimer) SET n = row;
RETURN 'Created forwardprimer nodes';
CREATE INDEX ON :forwardprimer(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/gene.csv" AS row CREATE (n:gene) SET n = row;
RETURN 'Created gene nodes';
CREATE INDEX ON :gene(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/geneflankingregion.csv" AS row CREATE (n:geneflankingregion) SET n = row;
RETURN 'Created geneflankingregion nodes';
CREATE INDEX ON :geneflankingregion(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/goannotation.csv" AS row CREATE (n:goannotation) SET n = row;
RETURN 'Created goannotation nodes';
CREATE INDEX ON :goannotation(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/goevidence.csv" AS row CREATE (n:goevidence) SET n = row;
RETURN 'Created goevidence nodes';
CREATE INDEX ON :goevidence(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/goevidencecode.csv" AS row CREATE (n:goevidencecode) SET n = row;
RETURN 'Created goevidencecode nodes';
CREATE INDEX ON :goevidencecode(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/goevidenceintermine_with.csv" AS row CREATE (n:goevidenceintermine_with) SET n = row;
RETURN 'Created goevidenceintermine_with nodes';
CREATE INDEX ON :goevidenceintermine_with(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/goldenpathfragment.csv" AS row CREATE (n:goldenpathfragment) SET n = row;
RETURN 'Created goldenpathfragment nodes';
CREATE INDEX ON :goldenpathfragment(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/goterm.csv" AS row CREATE (n:goterm) SET n = row;
RETURN 'Created goterm nodes';
CREATE INDEX ON :goterm(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/intergenicregion.csv" AS row CREATE (n:intergenicregion) SET n = row;
RETURN 'Created intergenicregion nodes';
CREATE INDEX ON :intergenicregion(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/intron.csv" AS row CREATE (n:intron) SET n = row;
RETURN 'Created intron nodes';
CREATE INDEX ON :intron(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/keywordsprotein.csv" AS row CREATE (n:keywordsprotein) SET n = row;
RETURN 'Created keywordsprotein nodes';
CREATE INDEX ON :keywordsprotein(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/location.csv" AS row CREATE (n:location) SET n = row;
RETURN 'Created location nodes';
CREATE INDEX ON :location(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/meshterm.csv" AS row CREATE (n:meshterm) SET n = row;
RETURN 'Created meshterm nodes';
CREATE INDEX ON :meshterm(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/microarrayoligo.csv" AS row CREATE (n:microarrayoligo) SET n = row;
RETURN 'Created microarrayoligo nodes';
CREATE INDEX ON :microarrayoligo(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/mirna.csv" AS row CREATE (n:mirna) SET n = row;
RETURN 'Created mirna nodes';
CREATE INDEX ON :mirna(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/mrna.csv" AS row CREATE (n:mrna) SET n = row;
RETURN 'Created mrna nodes';
CREATE INDEX ON :mrna(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/naturaltransposableelement.csv" AS row CREATE (n:naturaltransposableelement) SET n = row;
RETURN 'Created naturaltransposableelement nodes';
CREATE INDEX ON :naturaltransposableelement(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/ncrna.csv" AS row CREATE (n:ncrna) SET n = row;
RETURN 'Created ncrna nodes';
CREATE INDEX ON :ncrna(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/oligo.csv" AS row CREATE (n:oligo) SET n = row;
RETURN 'Created oligo nodes';
CREATE INDEX ON :oligo(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/ontology.csv" AS row CREATE (n:ontology) SET n = row;
RETURN 'Created ontology nodes';
CREATE INDEX ON :ontology(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/ontologyrelation.csv" AS row CREATE (n:ontologyrelation) SET n = row;
RETURN 'Created ontologyrelation nodes';
CREATE INDEX ON :ontologyrelation(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/ontologyterm.csv" AS row CREATE (n:ontologyterm) SET n = row;
RETURN 'Created ontologyterm nodes';
CREATE INDEX ON :ontologyterm(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/ontologytermrelations.csv" AS row CREATE (n:ontologytermrelations) SET n = row;
RETURN 'Created ontologytermrelations nodes';
CREATE INDEX ON :ontologytermrelations(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/ontologytermsynonym.csv" AS row CREATE (n:ontologytermsynonym) SET n = row;
RETURN 'Created ontologytermsynonym nodes';
CREATE INDEX ON :ontologytermsynonym(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/organism.csv" AS row CREATE (n:organism) SET n = row;
RETURN 'Created organism nodes';
CREATE INDEX ON :organism(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/overlappingestset.csv" AS row CREATE (n:overlappingestset) SET n = row;
RETURN 'Created overlappingestset nodes';
CREATE INDEX ON :overlappingestset(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/pcrproduct.csv" AS row CREATE (n:pcrproduct) SET n = row;
RETURN 'Created pcrproduct nodes';
CREATE INDEX ON :pcrproduct(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/pointmutation.csv" AS row CREATE (n:pointmutation) SET n = row;
RETURN 'Created pointmutation nodes';
CREATE INDEX ON :pointmutation(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/primer.csv" AS row CREATE (n:primer) SET n = row;
RETURN 'Created primer nodes';
CREATE INDEX ON :primer(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/protein.csv" AS row CREATE (n:protein) SET n = row;
RETURN 'Created protein nodes';
CREATE INDEX ON :protein(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/publication.csv" AS row CREATE (n:publication) SET n = row;
RETURN 'Created publication nodes';
CREATE INDEX ON :publication(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/regulatoryregion.csv" AS row CREATE (n:regulatoryregion) SET n = row;
RETURN 'Created regulatoryregion nodes';
CREATE INDEX ON :regulatoryregion(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/reverseprimer.csv" AS row CREATE (n:reverseprimer) SET n = row;
RETURN 'Created reverseprimer nodes';
CREATE INDEX ON :reverseprimer(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/rrna.csv" AS row CREATE (n:rrna) SET n = row;
RETURN 'Created rrna nodes';
CREATE INDEX ON :rrna(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/sequencecollection.csv" AS row CREATE (n:sequencecollection) SET n = row;
RETURN 'Created sequencecollection nodes';
CREATE INDEX ON :sequencecollection(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/sequencevariant.csv" AS row CREATE (n:sequencevariant) SET n = row;
RETURN 'Created sequencevariant nodes';
CREATE INDEX ON :sequencevariant(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/snorna.csv" AS row CREATE (n:snorna) SET n = row;
RETURN 'Created snorna nodes';
CREATE INDEX ON :snorna(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/snrna.csv" AS row CREATE (n:snrna) SET n = row;
RETURN 'Created snrna nodes';
CREATE INDEX ON :snrna(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/soterm.csv" AS row CREATE (n:soterm) SET n = row;
RETURN 'Created soterm nodes';
CREATE INDEX ON :soterm(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/synonym.csv" AS row CREATE (n:synonym) SET n = row;
RETURN 'Created synonym nodes';
CREATE INDEX ON :synonym(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/tfbindingsite.csv" AS row CREATE (n:tfbindingsite) SET n = row;
RETURN 'Created tfbindingsite nodes';
CREATE INDEX ON :tfbindingsite(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/threeprimeutr.csv" AS row CREATE (n:threeprimeutr) SET n = row;
RETURN 'Created threeprimeutr nodes';
CREATE INDEX ON :threeprimeutr(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/transcript.csv" AS row CREATE (n:transcript) SET n = row;
RETURN 'Created transcript nodes';
CREATE INDEX ON :transcript(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/transposableelement.csv" AS row CREATE (n:transposableelement) SET n = row;
RETURN 'Created transposableelement nodes';
CREATE INDEX ON :transposableelement(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/transposableelementinsertionsite.csv" AS row CREATE (n:transposableelementinsertionsite) SET n = row;
RETURN 'Created transposableelementinsertionsite nodes';
CREATE INDEX ON :transposableelementinsertionsite(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/trna.csv" AS row CREATE (n:trna) SET n = row;
RETURN 'Created trna nodes';
CREATE INDEX ON :trna(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/uniprotfeature.csv" AS row CREATE (n:uniprotfeature) SET n = row;
RETURN 'Created uniprotfeature nodes';
CREATE INDEX ON :uniprotfeature(id);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM "file:/{prj-path}/data/malariamine/utr.csv" AS row CREATE (n:utr) SET n = row;
RETURN 'Created utr nodes';
CREATE INDEX ON :utr(id);
